apiVersion: v1
kind: Pod
metadata:
  name: gossip-a
spec:
  hostNetwork: true
  containers:
    - name: gossip
      image: gossip
      imagePullPolicy: Never
      ports:
      - containerPort: 8888
---
apiVersion: v1
kind: Pod
metadata:
  name: gossip-b
spec:
  hostNetwork: true
  containers:
    - name: gossip
      image: gossip
      imagePullPolicy: Never
      ports:
      - containerPort: 8888
---
